---
title: "Table 1"
output: html_notebook
---
*Goal:* Generate demographics table along all assessed variables, convert to latex, and insert into paper as "table 1" or "table S1"
<!-- @TODO add in OR, CI and P value for PD to T1, merge T1 for DIG-PD into T1 for TERRE -->
## Libraries
```{r setup}
library(tidyverse)
library(data.table)
library(knitr)
library(table1)
Sys.setlocale("LC_MESSAGES", "en_US.utf8")
knitr::opts_knit$set(root.dir = "~/prs_ewas_integration/prs_analyses/")
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, cache.lazy = FALSE, autodep = TRUE)
```

## Load in and format TERRE data
```{r}
load("/home1/NEURO/SHARE_DECIPHER/processed_DNAm_data/2022/TERRE_processed_2022/1-TERRE_RG_filtered.RData") # PD_RG_filtered

mvals_combat <- minfi::getM(PD_RG_filtered)
(covars <- fread("/home1/NEURO/SHARE_DECIPHER/terre_meta_master.csv"))
covars$IID <- gsub("_PAE.*", "", covars$IID)
prs_mat <- fread("prsice_data/TERRE_PRSice.all_score")

# filtering
covars <- covars[patient %in% colnames(mvals_combat) & IID %in% prs_mat$IID]
prs_mat <- prs_mat[IID %in% covars$IID]
mvals_combat <- mvals_combat[, colnames(mvals_combat) %in% covars$patient]

# matching
covars <- covars[match(patient, colnames(mvals_combat))]
colnames(mvals_combat) <- covars$IID[match(covars$patient, colnames(mvals_combat))]
prs_mat <- prs_mat[match(IID, colnames(mvals_combat))]


computed_covars <- fread("prsice_data/TERRE.covariate")[IID %in% colnames(mvals_combat)]


all(covars$IID == computed_covars$IID)
covars <- cbind(covars[, -c("age", "men")], prs_mat[, .(SCORE1_AVG = `Pt_5e-08`)], computed_covars)
covars <- covars[, .(SCORE1_AVG, age, alcohol = ifelse(alcohol1 > 2, 1, 0), smoking = ifelse(smoking > 1, 1, 0), pesticides = ifelse(pesticides_work == 1, "Occupational", ifelse(pesticides_domestic == 1, "Domestic", "None")), PD=status, GPC1 = V3, GPC2 = V4, GPC3 = V5, PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10, head_trauma = head_trauma_loc, sex)]

all(covars$IID == prs_mat$IID)
all(prs_mat$IID == colnames(mvals_combat))
```

```{r}
library(boot)
get_or_covariate <- function(dat){
  reg <- summary(glm(PD ~ .,family="binomial", data=dat))
  coef.quantiles <- (reg$coefficients[-c(1), 1])
  ci <- (1.96 * reg$coefficients[-c(1), 2])
  ci.quantiles.u <- exp(coef.quantiles + ci)
  ci.quantiles.l <- exp(coef.quantiles - ci)
  coef.quantiles <- exp(coef.quantiles)
  to_plot <- data.frame(Coef = coef.quantiles, CI.U = ci.quantiles.u, CI.L = ci.quantiles.l,p.value = reg$coefficients[-c(1),4])
  return(to_plot)
}
make_quantiles <- function(prs_var,prsice_data,covariate,num_quant=5){
  prsice_data$prs_var <- prsice_data[,..prs_var]
  quant_data <- cbind(prsice_data[,.(prs_var)],covariate) %>%
      mutate(quant=factor(
        cut(prs_var,
            labels = F,
            breaks=unique(quantile(prs_var,num_quant,probs = seq(0,1,1/num_quant))),
            include.lowest=T
          )
      )) %>% dplyr::select(-prs_var)
  return(quant_data)
}
get_quantiles <- function(prs_var,prsice_data,covariate,num_quant=5){
  prsice_data$prs_var <- prsice_data[,..prs_var]
  quant_data <- cbind(prsice_data[,.(prs_var)],covariate) %>%
      mutate(quant=factor(
        cut(prs_var,
            labels = F,
            breaks=unique(quantile(prs_var,num_quant,probs = seq(0,1,1/num_quant))),
            include.lowest=T
          )
      )) %>% dplyr::select(-prs_var)
  reg <- summary(glm(PD ~quant+., family=binomial,data=quant_data))
  coef.quantiles <- (reg$coefficients[1:num_quant, 1])
  ci <- (1.96 * reg$coefficients[1:num_quant, 2])
  ci.quantiles.u <- exp(coef.quantiles + ci)
  ci.quantiles.l <- exp(coef.quantiles - ci)
  coef.quantiles <- exp(coef.quantiles)
  coef.quantiles[1] <- 1
  ci.quantiles.u[1] <- 1
  ci.quantiles.l[1] <- 1
  quantiles.for.table <- factor(levels(quant_data$quant),levels(quant_data$quant))
  to_plot <- data.frame(Coef = coef.quantiles, CI.U = ci.quantiles.u, CI.L = ci.quantiles.l, DEC = quantiles.for.table)
  return(to_plot)
}
or_w_grs <- make_quantiles("Pt_0.00030005",prs_mat,covars[,.(PD,sex,age,alcohol,smoking,pesticides=addNA(factor(pesticides,levels=c("None","Domestic","Occupational"))),head_trauma)],4)
or_estimates <- get_or_covariate(or_w_grs)
cross_quant <- get_quantiles("Pt_0.00030005",prs_mat,covars[,.(PD,age,sex,PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10,GPC1,GPC2,GPC3)]) %>% mutate(Sex = "Cross-sex", Threshold="best")

my.render.cont <- function(x) {
  with(stats.apply.rounding(stats.default(x), digits = 2), c("",
    "Mean (SD)" = sprintf("%s (&plusmn; %s)", MEAN, SD)
  ))
}
my.render.cat <- function(x) {
  c("", sapply(stats.default(x), function(y) {
    with(
      y,
      sprintf("%d (%0.0f %%)", FREQ, PCT)
    )
  }))
}
covars_table <- or_w_grs[, .(quant,sex, age, head_trauma, smoking, pesticides = recode(pesticides,"Missing"="NA"), alcohol, PD)] %>% mutate(
  PD = factor(PD, levels = c(1, 0), labels = c("Case", "Control")),
  head_trauma = factor(head_trauma, levels = c(0, 1), labels = c("Absent", "Present")),
  smoking = factor(smoking, levels = c(1, 0), labels = c("Smoker", "Non-smoker")),
  alcohol = factor(alcohol,levels=c(1,0),labels=c("Regular consumption","No consumption")),
  pesticides = factor(pesticides, levels = c("Occupational", "Domestic", "Missing")),
  sex = factor(sex, levels = c(1, 0), labels = c("Male", "Female")),
  quant = factor(quant,levels=c(1,2,3,4),labels =c("Quartile 1","Quartile 2", "Quartile 3", "Quartile 4"))
)

labels <- list(
  variables = list(
    sex = "Sex",
    age = "Age (years)",
    smoking = "Smoking status",
    alcohol = "Alcohol consumption",
    pesticides = "Pesticide exposure",
    head_trauma = "Prior head injury",
    quant = "GRS Quartile"
  ),
  groups = list("", "Parkinson's Status")
)
strata <- c(list(Total = covars_table), split(covars_table, covars_table$PD))
(finished_table <- table1(
  strata,
  labels,
  render.continuous = my.render.cont,
  render.categorical = my.render.cat,
  extra.col = list("Odds Ratio [95% CI]"=function(x,...){},"P-value"=function(x,...){})
  )
)
#t1kable(finished_table, format = "latex")
```
### Checking GRS SNPs available at different thresholds
```{r}
snps <- fread("TERRE_PRSice.snp")
snps[P  < 0.00030005]
snps[P  < 5e-8]
```
### Checking if these match with different mQTL
```{r}
godmc <- fread("~/sig_GWAS_godmc.txt")
godmc[V1 %in% c("rs356203", "rs28412513", "rs1372518")][order(V14)][!duplicated(V1)]
godmc[V1 %in% c("rs356203","rs1372518","rs10025915","rs3775439",   "rs151186370","rs2619362","rs10433953","rs2737032")][order(V14)][!duplicated(V1)]
```


## DIGPD table1
```{r}
IDs <- fread("~/genotype_qc/DIGPD_merged_post_imputation_QC/all_imputed_r2_30_rsid.fam")[, .(FID = V1, IID = V2)]
load("/home1/NEURO/SHARE_DECIPHER/processed_DNAm_data/2022/DIGPD_processed_2022/1-DIGPD_RG_filtered.RData") #DIGPD_RG_filtered
methy <- minfi::getM(DIGPD_RG_filtered)
digpd_pcs <- fread("~/genotype_qc/DIGPD_merged_post_imputation_QC/raw_data.preimpute.pcs")
digpd_metadata <- fread("/home1/NEURO/SHARE_DECIPHER/digpd_meta_master.csv") %>%
  mutate(FID=gsub("PAL_[0-9]*_", "", FID),IID = gsub("PAL_[0-9]*_", "", IID),patient=paste0(patient,".visit",visite)) %>%
  left_join(digpd_pcs %>% mutate(GPC1=PC1,GPC2=PC2,GPC3=PC3) %>%select(FID,IID,GPC1,GPC2,GPC3) ,by=c("FID","IID"))
methy <- methy[,colnames(methy) %in% digpd_metadata$patient]
meta <- digpd_metadata[digpd_metadata$patient %in% colnames(methy)]
ix <- na.omit(match(colnames(methy),meta$patient))
#methy <- methy[apply(methy,1,function(x)!any(is.infinite(x))),ix]
#PCs <- prcomp(methy,center = TRUE,rank. = 10)
prsice_cov <- na.omit(meta[!duplicated(IID),.(FID,IID,sex=men,age=Age,PD)])
covariate <- prsice_cov[,.(IID,sex,age)]
pre_table_data <- meta[prsice_cov$IID,on=.(IID),nomatch=0][visite == 1 | is.na(visite)][,.(IID,FID,age=Age, alcohol = ifelse(alcohol > 2, 1, 0), smoking = ifelse(smoking > 1, 1, 0), pesticides = ifelse(pesticides == 2, "Occupational", ifelse(pesticides== 1, "Domestic", "None")), PD, head_trauma, sex=men)]
```
```{r}
prsice_data_digpd <- fread("prsice_data/DIGPD_PRSice.all_score")
prsice_data_digpd <- prsice_data_digpd[pre_table_data,on="IID",nomatch=0]
pre_table_data <- pre_table_data[na.omit(match(prsice_data_digpd$IID,IID))]
all(pre_table_data$IID == prsice_data_digpd$IID)
```

```{r}
quantile_data_digpd <- make_quantiles("Pt_5e-08",prsice_data_digpd,pre_table_data[,.(PD,sex,age,alcohol,smoking,pesticides=addNA(factor(pesticides,levels=c("None","Domestic","Occupational"))),head_trauma)],4)
covars_table <- quantile_data_digpd[, .(quant,sex, age, head_trauma, smoking, pesticides = recode(pesticides,"Missing"="NA"), alcohol, PD)] %>% mutate(
  PD = factor(PD, levels = c(1, 0), labels = c("Case", "Control")),
  head_trauma = factor(head_trauma, levels = c(0, 1), labels = c("Absent", "Present")),
  smoking = factor(smoking, levels = c(1, 0), labels = c("Smoker", "Non-smoker")),
  alcohol = factor(alcohol,levels=c(1,0),labels=c("Regular consumption","No consumption")),
  pesticides = factor(pesticides, levels = c("Occupational", "Domestic", "Missing")),
  sex = factor(sex, levels = c(1, 0), labels = c("Male", "Female")),
  quant = factor(quant,levels=c(1,2,3,4),labels =c("Quartile 1","Quartile 2", "Quartile 3", "Quartile 4"))
)
or_table_digpd <- get_or_covariate(quantile_data_digpd[,.(PD,sex,age,quant)])

strata <- c(list(Total=covars_table),split(covars_table,covars_table$PD))
(finished_table_digpd <- table1(strata,labels,render.continuous=my.render.cont, render.categorical=my.render.cat, extra.col = list("Odds Ratio [95% CI]"=function(x,...){},"P-value"=function(x,...){})))
```


## TERRE Pesticide table
```{r}
library(mice)
env_data <- fread("/home1/NEURO/SHARE_DECIPHER/TERRE_pesticides/pesticides.csv")
mapping <- fread("/home1/NEURO/SHARE_DECIPHER/terre_meta_master.csv")
terre_prs <- fread("prsice_data/TERRE_PRSice.all_score")[, c("FID", "IID", "Pt_5e-08")]
colnames(terre_prs) <- c("FID", "IID", "SCORE1_AVG")
mapping$IID <- gsub("_PAE.*", "", mapping$IID)
env_data$num <- mapping$IID[match(env_data$num, mapping$patient)]

pest_missing <- read.csv("/home1/NEURO/SHARE_DECIPHER/TERRE_pesticides/pesticides.csv")
pest_imputed <- read.csv("/home1/NEURO/SHARE_DECIPHER/TERRE_pesticides/pesticides_imputed.csv")

pre_mids <- rbind(cbind(data.frame(X_imputation_ = 0), pest_missing)[, colnames(pest_imputed)], pest_imputed)
pre_mids$num <- as.character(pre_mids$num)
pre_mids <- pre_mids[pre_mids$num %in% mapping$patient & !is.na(mapping$IID[match(pre_mids$num, mapping$patient)]), ]
ix <- match(mapping$IID[match(pre_mids$num, mapping$patient)], terre_prs$IID)
pest_mids <- cbind(pre_mids, mapping[ix, .(status, sex = men)])

pest_names <- fread("~/pesticide-key.csv") %>% mutate(`English name` = ifelse(`English name` != Class & Class != "", paste0(`English name`, " (", Class, ")"), `English name`))
pest_key <- pest_names$Exposure
names(pest_key) <- pest_names$`English name`
pest_table <- pest_mids %>%
  select(-X_imputation_) %>%
  group_by(num) %>%
  summarize_at(vars(!contains("sex|status")), ~ mean(., na.rm = T)) %>%
  select(-num) %>%
  mutate(
    status = factor(status, levels = c(1, 0), labels = c("Case", "Control")),
    sex = factor(sex, levels = c(1, 0), labels = c("Male", "Female"))
  ) %>%
  rename(all_of(pest_key)) %>%
  select(-contains("_"))

(pesticide_table1 <- table1(~ . | status, overall = "Total", render.continuous = my.render.cont, data = pest_table))
```
